modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/qyl27/Xray"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "X-ray Mod"
authors = "qyl27"
description = '''
An easy way to find ores, caves or entities.
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "xray.mixins.json"

[[mixins]]
config = "xray-neoforge.mixins.json"
