modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/qyl27/architectury-loom-template/issues"
license = "CC BY 4.0"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
Start to make your fantastic Minecraft Mod!
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "${neoforge_architectury_version_range}"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "example.mixins.json"

[[mixins]]
config = "example-neoforge.mixins.json"
